const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Wires a release signing config into the generated `android/app/build.gradle`.
 *
 * The native project is regenerated by `expo prebuild`, so the signing setup
 * cannot live in a checked-in gradle file — it has to be re-applied on every
 * prebuild, which is what this plugin does.
 *
 * No secret is stored in the repository. The generated gradle reads four
 * properties, which come from `~/.gradle/gradle.properties`, the project's
 * (git-ignored) `android/gradle.properties`, `-P` flags, or the matching
 * `ORG_GRADLE_PROJECT_*` environment variables used by CI:
 *
 *   ALARMCLOCK_UPLOAD_STORE_FILE      path to the keystore
 *   ALARMCLOCK_UPLOAD_STORE_PASSWORD
 *   ALARMCLOCK_UPLOAD_KEY_ALIAS
 *   ALARMCLOCK_UPLOAD_KEY_PASSWORD
 *
 * When they are absent — a normal developer machine — the release build falls
 * back to the debug keystore exactly as the stock Expo template does, so
 * `expo run:android --variant release` keeps working locally. A real release
 * build fails loudly if signing is requested but incomplete, rather than
 * silently shipping a debug-signed artifact.
 */

const MARKER = '// alarm-clock: release signing';

const SIGNING_CONFIG = `
        ${MARKER}
        release {
            def storeFilePath = project.findProperty('ALARMCLOCK_UPLOAD_STORE_FILE')
            if (storeFilePath) {
                def resolvedStore = file(storeFilePath)
                if (!resolvedStore.exists()) {
                    // Concatenated rather than interpolated: this Groovy lives
                    // inside a JavaScript template literal.
                    throw new GradleException(
                        'ALARMCLOCK_UPLOAD_STORE_FILE points at ' + resolvedStore.absolutePath +
                        ', which does not exist.')
                }
                def storePasswordValue = project.findProperty('ALARMCLOCK_UPLOAD_STORE_PASSWORD')
                def keyAliasValue = project.findProperty('ALARMCLOCK_UPLOAD_KEY_ALIAS')
                def keyPasswordValue = project.findProperty('ALARMCLOCK_UPLOAD_KEY_PASSWORD')
                if (!storePasswordValue || !keyAliasValue || !keyPasswordValue) {
                    throw new GradleException(
                        'Incomplete signing configuration: set ALARMCLOCK_UPLOAD_STORE_PASSWORD, ' +
                        'ALARMCLOCK_UPLOAD_KEY_ALIAS and ALARMCLOCK_UPLOAD_KEY_PASSWORD.')
                }
                storeFile resolvedStore
                storePassword storePasswordValue
                keyAlias keyAliasValue
                keyPassword keyPasswordValue
            } else {
                // No upload key configured: keep the template's debug signing so
                // local release builds still install on a device.
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (modConfig) => {
    if (modConfig.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning only supports the Groovy build.gradle.');
    }
    if (modConfig.modResults.contents.includes(MARKER)) {
      return modConfig;
    }

    let contents = modConfig.modResults.contents;

    // 1. Add the `release` signing config next to the template's `debug` one.
    const signingConfigsMatch = contents.match(/signingConfigs\s*\{\s*\n(\s*)debug\s*\{/);
    if (!signingConfigsMatch) {
      throw new Error('Could not find the signingConfigs block in app/build.gradle.');
    }
    const debugBlockStart = contents.indexOf(signingConfigsMatch[0]);
    const insertAt = contents.indexOf('\n', contents.indexOf('signingConfigs', debugBlockStart));
    contents = `${contents.slice(0, insertAt)}\n${SIGNING_CONFIG}${contents.slice(insertAt)}`;

    // 2. Point the release build type at it.
    contents = contents.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
      '$1signingConfig signingConfigs.release'
    );

    if (!/release\s*\{[\s\S]*?signingConfig signingConfigs\.release/.test(contents)) {
      throw new Error('Could not point the release build type at signingConfigs.release.');
    }

    modConfig.modResults.contents = contents;
    return modConfig;
  });
};
